### ISSUE TITLE
Complete Documentation

### ISSUE THREAD

**Issue by saulpower** [SquareSquash/java#6]
The current documentation and implementation leave a lot of guess work to be had.  Currently my primary concerns are:
- How is the transmit method sending the crash report to the squash server?
- Where is the LogEntry interface from? (Not super clutch but just wondering)

Anyways it would be nice if the transmit method was included in the code base that would probably be ideal.

**Comment by JakeWharton** [comment]
See #1. This library can be used for JSON serializing the request on any platform accepting Java code (JVM, Android, GWT) and thus cannot include transmit functionality since it varies vastly between those.

`LogEntry` shouldn't be part of the docs.
